#!/bin/bash
if [ -x /sbin/brctl ]; then
	BRCTL="/sbin/brctl"
elif [ -x /usr/sbin/brctl ]; then
	BRCTL="/usr/sbin/brctl"
else
	echo "no bridge utils installed"
	exit 1
fi
if [ -x /sbin/ip ]; then
	switch=$(/sbin/ip route list | awk '/^default / { sub(/.* dev /, ""); print $1 }')
	/sbin/ip link set $1 up
else
	switch=$(/bin/netstat -rn | awk '/^0\.0\.0\.0/ { print $NF }')
	/sbin/ifconfig $1 0.0.0.0 up
fi
${BRCTL} addif ${switch} $1
